### PR TITLE
Fix a few more occurrences of divisive language

### PR DESCRIPTION
**Pull request by markusthoemmes**
As per title.

### CODE REVIEW

**Review by rhuss — COMMENTED** [review]
thanks, looks good to me !

Not sure why the tests are failing, but it's in the admin plugin which is currently on the way for being migrated (like all plugins within this repository)

/lgtm
/approve

**Comment by markusthoemmes** [comment]
@daisy-ycguo would you please have a look at the tests? This seems unrelated, maybe we should just drop the code now?

**Comment by navidshaikh** [comment]
We took off the tests https://github.com/knative/client-contrib/pull/88

**Pull request merged**
