### PR TITLE
Bump kafka plugin deps to source-pkg 0.5.0

### PR DESCRIPTION
**Pull request by markusthoemmes**
This solves https://snyk.io/vuln/SNYK-GOLANG-GOLANGORGXTEXTENCODINGUNICODE-609611 (as the relevant dep is bumped in github.com/maximilien/kn-source-pkg)

### CODE REVIEW

**Review by navidshaikh — COMMENTED** [review]
@daisy-ycguo : 

PTAL:
```
test/e2e/source_kafka_test.go:110:74: undefined: test.KnDefaultTestImage
```

We no longer uses a constant test image but build the test images in CI, to unblock you may carry helloworld image reference with this plugin and re-iterate on it in subsequent ?

**Comment by markusthoemmes** [comment]
@navidshaikh pushed an update that hardcodes the test image.

**Review by navidshaikh — APPROVED** [review]
/lgtm

**Pull request merged**
